#!/bin/sh
export CROSS_COMPILE=/opt/gcc-4.9.3-64-gnu/bin/mips64el-linux- 
#export CROSS_COMPILE=/opt/gcc-4.3-ls232-softfloat/bin/mipsel-linux-
make "$@"
if [ -e u-boot ];then
echo set architecture mips:isa64 > gdb.cmd
echo set mips abi o32 >> gdb.cmd
text_start=$((0x$(nm u-boot|grep __text_start|cut -f1 -d' ')))
bss_end=$((0x$(nm u-boot|grep __bss_end|cut -f1 -d' ')))
reloc=$(printf "0x%x" $(((0x90000000-($bss_end-$text_start))&0xffff0000)))
perl myreloc.pl $reloc >> gdb.cmd
#echo target remote 127.0.0.1:1234 >> gdb.cmd
#8ff60000
fi
