# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2003-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

obj-y	=  ls1a.o
obj-y	+= lowlevel_init.o tlb.o
obj-$(CONFIG_LOONGSON2K_SPI) += spi.o
obj-$(CONFIG_LOONGSON2K_I2C) += ls1a-i2c.o
obj-$(CONFIG_PCI) += pci.o
